# Generated by Django 5.2.5 on 2025-10-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parrafo',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='eventorepertorio',
            name='orden',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parrafo',
            name='orden',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
