# Generated by Django 5.2.5 on 2025-10-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_parrafo_options_eventorepertorio_orden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parrafo',
            name='orden',
        ),
    ]
