# Generated by Django 5.2.5 on 2025-11-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_remove_parrafo_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='url',
            field=models.CharField(max_length=750, null=True),
        ),
    ]
