# Generated by Django 5.2.5 on 2025-11-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_usuario_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='url',
            field=models.CharField(max_length=1750, null=True),
        ),
    ]
