# Generated by Django 5.2.5 on 2025-11-21 12:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('rutas', models.CharField(default='/ruta/por/defecto', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(max_length=80)),
                ('ci', models.CharField(max_length=80)),
                ('correo', models.CharField(default='sin_correo@ejemplo.com', max_length=100)),
                ('rol', models.CharField(choices=[('Admin', 'admin'), ('Padre', 'padre'), ('Madre', 'madre'), ('Docente', 'docente'), ('Alumno', 'Alumno')], default='Alumno', max_length=20)),
                ('clave', models.CharField(default='sin_clave', max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_cobro_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cobro_fin', models.DateTimeField()),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='tenan.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tema', models.CharField(blank=True, max_length=150, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='tenan.curso')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='tenan.gestion')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='tenan.materia')),
            ],
        ),
        migrations.CreateModel(
            name='padres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos_persona', to='tenan.persona')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padres_persona', to='tenan.persona')),
            ],
        ),
        migrations.CreateModel(
            name='CursoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_cursos', to='tenan.curso')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_persona', to='tenan.persona')),
            ],
        ),
        migrations.CreateModel(
            name='CobroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente'), ('Anulado', 'Anulado')], default='Pagado', max_length=20)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cobro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tenan.cobro')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobro_pagos', to='tenan.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Tarde', 'Tarde'), ('Justificado', 'Justificado')], default='Presente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='tenan.curso')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='tenan.gestion')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='tenan.materia')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='tenan.persona')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_documentos', to='tenan.documento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='tenan.persona')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gestion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_pago', to='tenan.gestion')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=200)),
                ('gestion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tenan.gestion')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_persona', to='tenan.persona')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_servicio', to='tenan.serviciospago')),
            ],
        ),
        migrations.AddField(
            model_name='cobro',
            name='servicio_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='tenan.serviciospago'),
        ),
        migrations.CreateModel(
            name='TramitePersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites_persona', to='tenan.persona')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_tramites', to='tenan.tramites')),
            ],
        ),
        migrations.CreateModel(
            name='SentralizadoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('t1_f1', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Trimestre 1 - Faceta 1')),
                ('t1_f2', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Trimestre 1 - Faceta 2')),
                ('t1_f3', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Trimestre 1 - Faceta 3')),
                ('t1_promedio', models.FloatField(blank=True, editable=False, null=True, verbose_name='Promedio Trimestre 1')),
                ('t1_auto_evaluacion', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Auto evaluación Trimestre 1')),
                ('t2_f1', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('t2_f2', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('t2_f3', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('t2_promedio', models.FloatField(blank=True, editable=False, null=True)),
                ('t2_auto_evaluacion', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('t3_f1', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('t3_f2', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('t3_f3', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('t3_promedio', models.FloatField(blank=True, editable=False, null=True)),
                ('t3_auto_evaluacion', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('promedio_anual', models.FloatField(blank=True, editable=False, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tenan.curso')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tenan.gestion')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tenan.materia')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tenan.persona')),
            ],
            options={
                'verbose_name': 'Nota Centralizada',
                'verbose_name_plural': 'Notas Centralizadas',
                'indexes': [models.Index(fields=['persona', 'gestion'], name='tenan_sentr_persona_a7e107_idx'), models.Index(fields=['curso', 'materia'], name='tenan_sentr_curso_i_f1f4e6_idx')],
                'unique_together': {('persona', 'materia', 'gestion', 'curso')},
            },
        ),
    ]
