# Generated by Django 5.2.5 on 2025-11-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.CharField(choices=[('Admin', 'admin'), ('Padre', 'padre'), ('Madre', 'madre'), ('Docente', 'docente'), ('Alumno', 'Alumno')], default='Alumno', max_length=20, null=True),
        ),
    ]
