# Generated by Django 5.2.5 on 2025-11-21 00:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenan', '0002_remove_asistencia_alumno_remove_asistencia_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=80)),
                ('director', models.CharField(max_length=80)),
                ('ubicacion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('rutas', models.CharField(default='/ruta/por/defecto', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('materia_fechaInicio', models.DateField(blank=True, null=True)),
                ('materia_fechaFin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(max_length=80)),
                ('ci', models.CharField(max_length=80)),
                ('correo', models.CharField(default='sin_correo@ejemplo.com', max_length=100)),
                ('clave', models.CharField(default='sin_clave', max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Tramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_cobro_inicio', models.DateTimeField()),
                ('fecha_cobro_fin', models.DateTimeField()),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='tenan.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tema', models.CharField(blank=True, max_length=150, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='tenan.curso')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='tenan.gestion')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='tenan.materia')),
            ],
        ),
        migrations.CreateModel(
            name='padres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos_persona', to='tenan.persona')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padres_persona', to='tenan.persona')),
            ],
        ),
        migrations.CreateModel(
            name='CursoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_cursos', to='tenan.curso')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_persona', to='tenan.persona')),
            ],
        ),
        migrations.CreateModel(
            name='CobroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente'), ('Anulado', 'Anulado')], default='Pagado', max_length=20)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cobro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tenan.cobro')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobro_pagos', to='tenan.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Tarde', 'Tarde'), ('Justificado', 'Justificado')], default='Presente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='tenan.curso')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='tenan.gestion')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='tenan.materia')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='tenan.persona')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_documentos', to='tenan.documento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='tenan.persona')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_persona', to='tenan.persona')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_roles_rel', to='tenan.rol')),
            ],
        ),
        migrations.CreateModel(
            name='SentralizadoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('t1_f1', models.FloatField(blank=True, null=True)),
                ('t1_f2', models.FloatField(blank=True, null=True)),
                ('t1_f3', models.FloatField(blank=True, null=True)),
                ('t1_promedio', models.FloatField(blank=True, null=True)),
                ('t1_auto_evaluacion', models.FloatField(blank=True, null=True)),
                ('t2_f1', models.FloatField(blank=True, null=True)),
                ('t2_f2', models.FloatField(blank=True, null=True)),
                ('t2_f3', models.FloatField(blank=True, null=True)),
                ('t2_promedio', models.FloatField(blank=True, null=True)),
                ('t2_auto_evaluacion', models.FloatField(blank=True, null=True)),
                ('t3_f1', models.FloatField(blank=True, null=True)),
                ('t3_f2', models.FloatField(blank=True, null=True)),
                ('t3_f3', models.FloatField(blank=True, null=True)),
                ('t3_promedio', models.FloatField(blank=True, null=True)),
                ('t3_auto_evaluacion', models.FloatField(blank=True, null=True)),
                ('promedio_anual', models.FloatField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tenan.curso')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tenan.gestion')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tenan.materia')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tenan.persona')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gestion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_pago', to='tenan.gestion')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=200)),
                ('gestion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tenan.gestion')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_persona', to='tenan.persona')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_servicio', to='tenan.serviciospago')),
            ],
        ),
        migrations.AddField(
            model_name='cobro',
            name='servicio_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='tenan.serviciospago'),
        ),
        migrations.CreateModel(
            name='TramitePersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites_persona', to='tenan.persona')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_tramites', to='tenan.tramites')),
            ],
        ),
    ]
